'use strict';
const tr={en:{name:'Masha Maykova',nav:['Paintings','Graphic Art','About','Contact'],artist:'Masha Maykova · Artist',note:'Select a work to view in detail',more:'Show more works',rights:'All rights reserved',back:'Back to works ↑',solo:'Solo exhibitions',group:'Group exhibitions',essays:'Writing on the work',archive:'From the artist’s archive',untitled:'Title not recorded',zoom:'Zoom in',out:'Fit to screen',menu:'Menu',close:'Close',education:'Education & membership',contact:'For exhibition, collection and collaboration enquiries.',pending:'Contact details will be added shortly.',bioLead:'Masha Maykova is an artist based in Moscow. Her paintings and graphic works bring together everyday life, interiors, landscapes and the intimate world of human relationships.',bio:'Born in Yaroslavl in 1952, she studied at the Abramtsevo School of Industrial Art from 1968 to 1972 and at the Art Faculty of the Moscow Technological Institute from 1973 to 1977. She joined the Union of Artists of the USSR in 1983. Her work has been shown in Russia and internationally, and is held in private collections in Russia, Europe, the United States and Canada.',study:['1968–1972 · Abramtsevo School of Industrial Art','1973–1977 · Moscow Technological Institute, Art Faculty','1983 · Joined the Union of Artists of the USSR']},ru:{name:'Маша Майкова',nav:['Живопись','Графика','Об авторе','Контакты'],artist:'Маша Майкова · Художник',note:'Нажмите на работу, чтобы рассмотреть её крупнее',more:'Показать ещё',rights:'Все права защищены',back:'К работам ↑',solo:'Персональные выставки',group:'Групповые выставки',essays:'О творчестве',archive:'Из архива художницы',untitled:'Название не указано',zoom:'Увеличить',out:'Вписать в экран',menu:'Меню',close:'Закрыть',education:'Образование и членство',contact:'По вопросам выставок, приобретения работ и сотрудничества.',pending:'Контактные данные скоро появятся.',bioLead:'Маша Майкова — художник, живёт и работает в Москве. В её живописи и графике встречаются повседневная жизнь, интерьеры, пейзажи и близкий мир человеческих отношений.',bio:'Родилась в Ярославле в 1952 году. В 1968–1972 годах училась в Абрамцевском художественно-промышленном училище, в 1973–1977 годах — на художественном факультете Московского технологического института. С 1983 года — член Союза художников СССР. Участвовала в российских и международных выставках. Её работы находятся в частных собраниях России, Европы, США и Канады.',study:['1968–1972 · Абрамцевское художественно-промышленное училище','1973–1977 · Московский технологический институт, художественный факультет','1983 · Вступление в Союз художников СССР']}};
const routes=['paintings','graphic-art','about','contact'];
let lang=new URLSearchParams(location.search).get('lang')==='ru'?'ru':'en',route='paintings',shown=30,exhibitionType='solo',activeWorks=[],activeIndex=0,lastFocus=null;
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const titleOf=w=>w.title?.[lang]||w.title?.ru||tr[lang].name;
function metadata(w){return [w.medium?.[lang],w.dimensions?`${w.dimensions} ${lang==='ru'?'см':'cm'}${w.dimension_note?' ('+w.dimension_note[lang]+')':''}`:''].filter(Boolean).join(' · ')}
function heading(i){return `<div class="page-heading"><div><p class="eyebrow">${tr[lang].artist}</p><h1>${tr[lang].nav[i]}</h1></div>${i<2?`<p class="gallery-note">${tr[lang].note}</p>`:''}</div>`}
function artworkImage(w,thumb=false){return `assets/${w.id}${w.id==='0096'?'-cropped':''}${thumb?'-thumb':''}.${w.id==='0096'?'svg':'webp'}`}

// Only reviewed photographs with distracting surroundings are listed here.
// Photographs with color scales and neat white/black borders stay untouched.
// Coordinates are fractions of the original image; source pixels are preserved.
const ARTWORK_CROPS={"0084":[0.06699999999999999,0,0.99,1],"0107":[0.06999999999999999,0.058,0.915,0.972],"0280":[0,0.05,1,0.85],"0411":[0,0.09799999999999999,1,0.962],"0549":[0.02,0,0.979,0.972],"0550":[0.029,0.04,0.968,0.962],"0551":[0.024,0.016,0.982,0.975],"0568":[0.02,0.012999999999999998,0.967,0.98],"0573":[0.007,0.001,0.998,0.995],"0579":[0.012999999999999998,0.012999999999999998,0.97,0.974],"0588":[0.033,0.009999999999999998,0.974,0.974],"0589":[0.027,0.007,0.967,0.967],"0590":[0.020999999999999998,0.020999999999999998,0.967,0.953],"0591":[0.02,0.024,0.967,0.954],"0592":[0.026,0.013999999999999999,0.97,0.956],"0593":[0,0.047,0.871,0.783],"0704":[0.063,0,0.92,1],"0705":[0.08199999999999999,0.030000000000000002,0.92,1,180],"0706":[0.049,0,0.915,0.981],"0707":[0.11499999999999999,0,0.92,0.99],"0708":[0.108,0,0.93,0.992],"0709":[0.127,0,0.9400000000000001,0.986],"0710":[0.129,0,0.9410000000000001,0.981],"0711":[0.128,0,0.9380000000000001,0.983],"0712":[0.12,0,0.935,0.982],"0660":[0,0.009545454545454546,1,1],"0058":[0.020833333333333332,0.02727272727272727,1,1]};
function artworkMarkup(w,thumb=false,index=0,viewer=true){
 const crop=ARTWORK_CROPS[w.id], label=esc(titleOf(w)), id=thumb||!viewer?'':' id="large-image"';
 if(!crop)return `<img${id} data-artwork="${w.id}" src="${artworkImage(w,thumb)}" alt="${label}" loading="${thumb&&index>=6?'lazy':'eager'}" width="${w.width}" height="${w.height}">`;
 const x=crop[0]*w.width,y=crop[1]*w.height,width=(crop[2]-crop[0])*w.width,height=(crop[3]-crop[1])*w.height;
 const transform=crop[4]?` transform="rotate(${crop[4]} ${x+width/2} ${y+height/2})"`:'';
 return `<svg${id} data-artwork="${w.id}" class="cropped-artwork" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="${label}" viewBox="${x} ${y} ${width} ${height}" width="${width}" height="${height}" preserveAspectRatio="${thumb?'xMidYMax':'xMidYMid'} meet"><svg x="${x}" y="${y}" width="${width}" height="${height}" viewBox="${x} ${y} ${width} ${height}" overflow="hidden"><image href="assets/${w.id}${thumb?'-thumb':''}.webp" width="${w.width}" height="${w.height}"${transform}/></svg></svg>`;
}

function gallery(){activeWorks=ARTWORKS.filter(w=>w.category===route);return `<div class="gallery">${activeWorks.slice(0,shown).map((w,i)=>`<figure class="artwork"><button data-work="${i}" aria-label="${esc(titleOf(w))}">${artworkMarkup(w,true,i)}</button><figcaption><span class="caption-title">${esc(w.title?.[lang]||w.title?.ru||'')}${w.year?`<span class="year">${w.year}</span>`:''}</span><span class="meta">${esc(metadata(w))}</span></figcaption></figure>`).join('')}</div>${shown<activeWorks.length?`<div class="load-wrap"><button class="load-more">${tr[lang].more}</button></div>`:''}`}
function about(){let w=ARTWORKS.find(w=>w.id===ABOUT_ART)||ARTWORKS[0];return `<div class="bio-layout"><figure class="bio-art">${artworkMarkup(w,false,0,false)}<figcaption>${esc(titleOf(w))}${w.year?', '+w.year:''}</figcaption></figure><div class="bio-text"><p class="lead">${tr[lang].bioLead}</p><p>${tr[lang].bio}</p><section class="film-section"><div class="film-player"><iframe src="https://player.vimeo.com/video/155233190?dnt=1&title=0&byline=0&portrait=0" title="Exhibition — Grigory Maykov" loading="lazy" allow="fullscreen; picture-in-picture; encrypted-media" allowfullscreen></iframe></div></section></div></div><section class="essay-section"><h2 class="section-title">${tr[lang].essays}</h2>${ESSAYS.map(e=>`<article class="essay"><h3>${esc(e.title[lang])}</h3><div class="essay-text">${e.body[lang].map(p=>`<p>${esc(p)}</p>`).join('')}<p class="essay-source">${esc(e.source[lang])}</p></div></article>`).join('')}</section><section class="about-exhibitions" aria-labelledby="exhibitions-heading"><h2 id="exhibitions-heading">${lang==='ru'?'Выставки':'Exhibitions'}</h2><div id="exhibitions-content">${exhibitions()}</div></section>`}
function exhibitions(){
 const events=['solo','group'].flatMap(type=>EXHIBITIONS[type].map(e=>({...e,type}))).sort((a,b)=>Number(a.year)-Number(b.year));
 const years=[...new Set(events.map(e=>e.year))];
 const groups=years.map(year=>({year,events:events.filter(e=>e.year===year)}));
 const boundaries=[];let running=0;
 groups.forEach((g,i)=>{running+=g.events.length;if(i<groups.length-1)boundaries.push({index:i+1,count:running})});
 const first=boundaries.reduce((best,b)=>Math.abs(b.count-events.length/3)<Math.abs(best.count-events.length/3)?b:best);
 const second=boundaries.filter(b=>b.index>first.index).reduce((best,b)=>Math.abs(b.count-events.length*2/3)<Math.abs(best.count-events.length*2/3)?b:best);
 const columns=[groups.slice(0,first.index),groups.slice(first.index,second.index),groups.slice(second.index)];
 return `<div class="exhibition-columns">${columns.map(column=>`<div class="exhibition-column">${column.map(g=>`<section class="exhibition-year-group"><div>${g.events.map(e=>`<article class="exhibition-entry"><p class="exhibition-kind"><span class="entry-year">${e.year}</span><span>${lang==='ru'?(e.type==='solo'?'Персональная':'Групповая'):(e.type==='solo'?'Solo':'Group')}</span></p><h4 class="exhibition-title">${esc(e.title[lang])}</h4><p class="exhibition-location">${esc(e.location[lang])}</p></article>`).join('')}</div></section>`).join('')}</div>`).join('')}</div>`
}
function contact(){let w=ARTWORKS.find(w=>w.id===CONTACT_ART)||ARTWORKS[0];return `<div class="contact-layout"><img src="${artworkImage(w)}" alt="${esc(titleOf(w))}"><div class="contact-copy"><h2>${tr[lang].name}</h2><p>${tr[lang].contact}</p><a class="contact-phone" href="tel:+79653140496">+7 965 314 04 96</a><div class="social-links"><a href="https://t.me/+79653140496" target="_blank" rel="noopener" aria-label="Telegram" title="Telegram"><svg viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M21.6 3.5 18.3 20c-.25 1.17-.9 1.45-1.84.9l-5.05-3.73-2.44 2.35c-.27.27-.5.5-1.02.5l.36-5.13L17.65 6c.4-.36-.09-.56-.61-.2L5.5 13.08.53 11.52c-1.08-.34-1.1-1.08.22-1.6L20.16 2.4c.9-.34 1.7.21 1.44 1.1Z"/></svg></a><a href="https://wa.me/79653140496" target="_blank" rel="noopener" aria-label="WhatsApp" title="WhatsApp"><svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.55" stroke-linecap="round" stroke-linejoin="round"><path d="M20.6 11.6a8.8 8.8 0 0 1-13 7.8L3 20.8l1.4-4.4A8.8 8.8 0 1 1 20.6 11.6Z"/><path d="m8 7.2 1.6-.1 1.1 2.6-1.1 1c.8 1.7 1.9 2.8 3.6 3.5l1-1.2 2.7 1.2v1.6c-1.9 2.5-7.9-.3-9.6-4.9-.5-1.4-.4-2.7.7-3.7Z"/></svg></a><a href="https://www.facebook.com/profile.php?id=100006250209629" target="_blank" rel="noopener" aria-label="Facebook" title="Facebook"><svg viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M14 22v-9h3l.5-3H14V8c0-.9.3-1.5 1.6-1.5H18V3.2c-.4-.1-1.8-.2-3.3-.2C11.5 3 10 4.9 10 8v2H7v3h3v9Z"/></svg></a><a href="https://www.instagram.com/mashamaykova/" target="_blank" rel="noopener" aria-label="Instagram — @mashamaykova" title="Instagram"><svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.7"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r="1" fill="currentColor" stroke="none"/></svg></a><a href="mailto:mashamaykova@gmail.com" aria-label="Email" title="Email"><svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="5" width="18" height="14" rx="1"/><path d="m3 6 9 7 9-7"/></svg></a></div></div></div>`}
function render(reset=true){updateMenuReturn();let hash=location.hash.slice(1);if(hash==='exhibitions'){hash='about';history.replaceState(null,'',location.pathname+location.search+'#about')}route=routes.includes(hash)?hash:'paintings';document.body.dataset.page=route;if(reset)shown=30;const i=routes.indexOf(route);document.documentElement.lang=lang;document.title=`${tr[lang].name} — ${tr[lang].nav[i]}`;$('nav').innerHTML=routes.map((r,j)=>`<a href="#${r}" ${r===route?'aria-current="page"':''}>${tr[lang].nav[j]}</a>`).join('');$('.signature').textContent=tr[lang].name;$('.footer-name').textContent=tr[lang].name;$('#copyright').textContent=`© ${new Date().getFullYear()} ${tr[lang].name}. ${tr[lang].rights}.`;$('#back-top').textContent=tr[lang].back;$('.menu-toggle').textContent=tr[lang].menu;document.querySelectorAll('[data-lang]').forEach(b=>{b.classList.toggle('active',b.dataset.lang===lang);b.setAttribute('aria-pressed',b.dataset.lang===lang)});$('#main').innerHTML=heading(i)+(i<2?gallery():i===2?about():contact());$('#close').setAttribute('aria-label',tr[lang].close);$('#prev').setAttribute('aria-label',lang==='ru'?'Предыдущая работа':'Previous artwork');$('#next').setAttribute('aria-label',lang==='ru'?'Следующая работа':'Next artwork')}
function showImage(){const w=activeWorks[activeIndex];$('#image-stage').classList.remove('zoomed');$('#zoom').textContent='+';$('#zoom').setAttribute('aria-label',tr[lang].zoom);$('#image-stage').innerHTML=artworkMarkup(w);$('#viewer-count').textContent=`${activeIndex+1} / ${activeWorks.length}`;$('#viewer-caption').innerHTML=`<div>${esc(titleOf(w))}${w.year?`, ${w.year}`:''}</div><div class="caption-meta">${esc(metadata(w))}</div>`}
function openWork(index){activeIndex=index;lastFocus=document.activeElement;showImage();$('#lightbox').showModal();document.body.style.overflow='hidden';$('#close').focus()}
function step(d){activeIndex=(activeIndex+d+activeWorks.length)%activeWorks.length;showImage()}
function zoom(){const enabled=$('#image-stage').classList.toggle('zoomed');$('#zoom').textContent=enabled?'−':'+';$('#zoom').setAttribute('aria-label',tr[lang][enabled?'out':'zoom'])}
$('#main').addEventListener('click',e=>{const b=e.target.closest('[data-work]');if(b)openWork(Number(b.dataset.work));if(e.target.closest('.load-more')){shown+=30;render(false)}});
document.querySelectorAll('[data-lang]').forEach(b=>b.addEventListener('click',()=>{lang=b.dataset.lang;const u=new URL(location);if(lang==='ru')u.searchParams.set('lang','ru');else u.searchParams.delete('lang');history.replaceState(null,'',u);render(false)}));
$('.menu-toggle').addEventListener('click',()=>{const on=$('header').classList.toggle('menu-open');$('.menu-toggle').setAttribute('aria-expanded',on)});
window.addEventListener('hashchange',()=>{$('header').classList.remove('menu-open');$('.menu-toggle').setAttribute('aria-expanded','false');render();window.scrollTo({top:0,behavior:'instant'})});
$('#close').addEventListener('click',()=>$('#lightbox').close());$('#lightbox').addEventListener('close',()=>{document.body.style.overflow='';lastFocus?.focus()});$('#prev').addEventListener('click',()=>step(-1));$('#next').addEventListener('click',()=>step(1));$('#zoom').addEventListener('click',zoom);$('#image-stage').addEventListener('click',zoom);$('#lightbox').addEventListener('keydown',e=>{if(e.key==='ArrowRight'){e.preventDefault();step(1)}if(e.key==='ArrowLeft'){e.preventDefault();step(-1)}});let touchX=0;$('#image-stage').addEventListener('touchstart',e=>touchX=e.changedTouches[0].clientX,{passive:true});$('#image-stage').addEventListener('touchend',e=>{if($('#image-stage').classList.contains('zoomed'))return;const dx=e.changedTouches[0].clientX-touchX;if(Math.abs(dx)>60)step(dx<0?1:-1)},{passive:true});
render();

function alignBackgroundVeil(){updateMenuReturn();document.body.style.setProperty('--header-bottom',Math.max(0,document.querySelector('header').getBoundingClientRect().bottom)+'px')}
new ResizeObserver(alignBackgroundVeil).observe(document.querySelector('header'));
window.addEventListener('scroll',alignBackgroundVeil,{passive:true});
window.addEventListener('resize',alignBackgroundVeil);
alignBackgroundVeil();

/* Return to navigation without re-rendering or losing loaded gallery items. */
function updateMenuReturn(){
 const button=document.getElementById('return-menu');
 if(!button)return;
 button.hidden=window.scrollY<Math.max(240,window.innerHeight*.45);
 button.querySelector('span:last-child').textContent=lang==='ru'?'К меню':'Menu';
 button.setAttribute('aria-label',lang==='ru'?'Вернуться к основному меню':'Return to main menu');
}
document.getElementById('return-menu').addEventListener('click',()=>{
 if(window.matchMedia('(max-width:760px)').matches){
  $('header').classList.add('menu-open');
  $('.menu-toggle').setAttribute('aria-expanded','true');
 }
 window.scrollTo({top:0,behavior:'instant'});
 ($('nav a[aria-current="page"]')||$('.menu-toggle')).focus({preventScroll:true});
 updateMenuReturn();
});
updateMenuReturn();
